[profile.default]
solc = "0.8.28"
evm_version = "cancun"
#via_ir = true
evm_version = "cancun"
bytecode_hash = "ipfs"
optimizer_runs = 1_000_000
gas_limit = "18446744073709551615"
libs = ['lib']
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]
match_path = "test/unit/*.sol"
verbosity = 3
fs_permissions = [
    { access = "write", path = "./script/optimized-deployer-meta" },
    { access = "write", path = "./script/unoptimized-deployer-meta" },
]
ignored_error_codes = []

[profile.default.fuzz]
seed = "0xd679d565cc78d6c78308f18282cb070e065bf4c517fbd552922d47f2127a2bbc"

[profile.integration]
match_path = "test/integration/*.sol"

[profile.coverage-integration]
match_path = "test/integration/*.sol"

[profile.differential]
fs_permissions = [{ access = "read", path = "./reference/balancer-v2-monorepo" }]
match_path     = "test/differential/*.sol"

[profile.differential.fuzz]
runs = 10_000

[profile.ci.fuzz]
runs = 10_000

[fmt]
bracket_spacing   = true
wrap_comments     = true
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
